### ISSUE TITLE
大佬，该更新5.4.108了！哈哈

### ISSUE THREAD

**Issue by zhb7670** [mingxiaoyu/N1imagebuilder#7]
大佬，该更新5.4.108了！哈哈

**Comment by mingxiaoyu** [comment]
在更新ing
等更新好哦OpenWRT 之后再打包
@zhb7670 
大概是5点之后吧

**Comment by zhb7670** [comment]
> 在更新ing
> 等更新好哦OpenWRT 之后再打包
> @zhb7670
> 大概是5点之后吧

谢谢！大佬

**Comment by zhb7670** [comment]
怎么没更新么？大佬？

**Comment by mingxiaoyu** [comment]
openwrt更新了啊。
只是不更新56+而已，f大上了些实验性的东西。没必要追这个56+。55------＞56 这样的小版本。几乎不会提升。而已还上实验性的东西。稳定为主。

**Comment by zhb7670** [comment]
喔，知道了！请问下载固件地址是如下地址？https://github.com/mingxiaoyu/N1Openwrt/releases/download/20210402/openwrt-armvirt-64-default-rootfs.tar.gz

**Comment by mingxiaoyu** [comment]
这个是op，但是没打包 ，不能用在N1。

https://github.com/mingxiaoyu/N1imagebuilder/releases/tag/20210402

这是打包好的。

手机码字不易

**Comment by zhb7670** [comment]
好吧，我还以为可以用在N1呢，我是小白，我不会打包！😂

**Comment by zhb7670** [comment]
我fork你的我不会玩！我想自动安装编译，自动打包，直接更新N1

**Comment by mingxiaoyu** [comment]
https://github.com/mingxiaoyu/N1imagebuilder/releases/download/20210402/N1_55_Openwrt.img.xz

这个可以用在n1....
